#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-CGI-Untaint
version:      1.01
version_from: lib/Test/CGI/Untaint.pm
installdirs:  site
requires:
    CGI::Untaint:                  0.82
    Test::Builder::Tester:         0.09

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_02
